apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "nginx-gcr-deployment"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "nginx"
    spec:
      containers:
      - image: k8s.gcr.io/nginx
        imagePullPolicy: Always
        name: "nginx"
        ports:
        - containerPort: 80